name: Rust

on:
  push:
    branches: ["github-actions"]
#  pull_request:
#    branches: ["github-actions"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  publish:
    if: "!contains(github.event.head_commit.message, 'chore')"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git # copied from here: https://stackoverflow.com/questions/69839851/github-actions-copy-git-user-name-and-user-email-from-last-commit
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)" 
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-release
        run: cargo install cargo-release
      - name: Release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo release --workspace patch --execute --no-confirm --no-verify --no-push